-- SET max_wal_size = '4GB';
CREATE TABLE IF NOT EXISTS scores (
    id SERIAL PRIMARY KEY,
    county_code VARCHAR(50),
    district_code VARCHAR(50),
    district_name TEXT,
    school_code VARCHAR(50),
    school_name TEXT,
    type_id INTEGER,
    filler TEXT,
    test_year INTEGER,
    test_type VARCHAR(50),
    test_id INTEGER,
    student_group_id INTEGER,
    grade INTEGER,
    total_students_enrolled INTEGER,
    total_students_tested INTEGER,
    total_students_tested_with_scores INTEGER,
    mean_scale_score REAL,
    pct_std_exceeded REAL,
    count_std_exceeded INTEGER,
    pct_std_met REAL,
    count_std_met INTEGER,
    pct_std_met_and_above REAL,
    count_std_met_and_above INTEGER,
    pct_std_nearly_met REAL,
    count_std_nearly_met INTEGER,
    pct_std_not_met REAL,
    count_std_not_met INTEGER,
    overall_total INTEGER,
    area_1_pct_above_std REAL,
    area_1_count_above_std INTEGER,
    area_1_pct_near_std REAL,
    area_1_count_near_std INTEGER,
    area_1_pct_below_std REAL,
    area_1_count_below_std INTEGER,
    area_1_total INTEGER,
    area_2_pct_above_std REAL,
    area_2_count_above_std INTEGER,
    area_2_pct_near_std REAL,
    area_2_count_near_std INTEGER,
    area_2_pct_below_std REAL,
    area_2_count_below_std INTEGER,
    area_2_total INTEGER,
    area_3_pct_above_std REAL,
    area_3_count_above_std INTEGER,
    area_3_pct_near_std REAL,
    area_3_count_near_std INTEGER,
    area_3_pct_below_std REAL,
    area_3_count_below_std INTEGER,
    area_3_total INTEGER,
    area_4_pct_above_std REAL,
    area_4_count_above_std INTEGER,
    area_4_pct_near_std REAL,
    area_4_count_near_std INTEGER,
    area_4_pct_below_std REAL,
    area_4_count_below_std INTEGER,
    area_4_total INTEGER,
    cmp_area_1_pct_above_std REAL,
    cmp_area_1_count_above_std INTEGER,
    cmp_area_1_pct_near_std REAL,
    cmp_area_1_count_near_std INTEGER,
    cmp_area_1_pct_below_std REAL,
    cmp_area_1_count_below_std INTEGER,
    cmp_area_1_total INTEGER,
    cmp_area_2_pct_above_std REAL,
    cmp_area_2_count_above_std INTEGER,
    cmp_area_2_pct_near_std REAL,
    cmp_area_2_count_near_std INTEGER,
    cmp_area_2_pct_below_std REAL,
    cmp_area_2_count_below_std INTEGER,
    cmp_area_2_total INTEGER
);

COPY scores (
    county_code,
    district_code,
    district_name,
    school_code,
    school_name,
    type_id,
    filler,
    test_year,
    test_type,
    test_id,
    student_group_id,
    grade,
    total_students_enrolled,
    total_students_tested,
    total_students_tested_with_scores,
    mean_scale_score,
    pct_std_exceeded,
    count_std_exceeded,
    pct_std_met,
    count_std_met,
    pct_std_met_and_above,
    count_std_met_and_above,
    pct_std_nearly_met,
    count_std_nearly_met,
    pct_std_not_met,
    count_std_not_met,
    overall_total,
    area_1_pct_above_std,
    area_1_count_above_std,
    area_1_pct_near_std,
    area_1_count_near_std,
    area_1_pct_below_std,
    area_1_count_below_std,
    area_1_total,
    area_2_pct_above_std,
    area_2_count_above_std,
    area_2_pct_near_std,
    area_2_count_near_std,
    area_2_pct_below_std,
    area_2_count_below_std,
    area_2_total,
    area_3_pct_above_std,
    area_3_count_above_std,
    area_3_pct_near_std,
    area_3_count_near_std,
    area_3_pct_below_std,
    area_3_count_below_std,
    area_3_total,
    area_4_pct_above_std,
    area_4_count_above_std,
    area_4_pct_near_std,
    area_4_count_near_std,
    area_4_pct_below_std,
    area_4_count_below_std,
    area_4_total,
    cmp_area_1_pct_above_std,
    cmp_area_1_count_above_std,
    cmp_area_1_pct_near_std,
    cmp_area_1_count_near_std,
    cmp_area_1_pct_below_std,
    cmp_area_1_count_below_std,
    cmp_area_1_total,
    cmp_area_2_pct_above_std,
    cmp_area_2_count_above_std,
    cmp_area_2_pct_near_std,
    cmp_area_2_count_near_std,
    cmp_area_2_pct_below_std,
    cmp_area_2_count_below_std,
    cmp_area_2_total)
FROM '/raw/scores.txt' DELIMITER '^' CSV NULL '' HEADER;

CREATE INDEX ON scores (district_code, type_id);
CREATE INDEX ON scores (district_code);
