CREATE TABLE IF NOT EXISTS grads (
    id SERIAL PRIMARY KEY,
    reporting_year VARCHAR(50),
    agglevel VARCHAR(50),
    county_code VARCHAR(50),
    district_code VARCHAR(50),
    school_code VARCHAR(50),
    county_name VARCHAR(200),
    district_name VARCHAR(200),
    school_name VARCHAR(200),
    charter_school VARCHAR(50),
    dass VARCHAR(50),
    reporting_category VARCHAR(50),
    cohort_students INTEGER,
    cnt_reg_hs_grads INTEGER,
    rate_reg_hs_grads REAL,
    cnt_met_uc_reqs INTEGER,
    rate_met_uc_reqs REAL,
    cnt_biliteracy INTEGER,
    rate_biliteracy REAL,
    cnt_merit INTEGER,
    rate_merit REAL,
    cnt_non_grad_completers INTEGER,
    rate_non_grad_completers REAL,
    cnt_transfers INTEGER,
    rate_transfers REAL,
    cnt_dropout INTEGER,
    rate_dropout REAL
);

COPY grads (
    reporting_year,
    agglevel,
    county_code,
    district_code,
    school_code,
    county_name,
    district_name,
    school_name,
    charter_school,
    dass,
    reporting_category,
    cohort_students,
    cnt_reg_hs_grads,
    rate_reg_hs_grads,
    cnt_met_uc_reqs,
    rate_met_uc_reqs,
    cnt_biliteracy,
    rate_biliteracy,
    cnt_merit,
    rate_merit,
    cnt_non_grad_completers,
    rate_non_grad_completers,
    cnt_transfers,
    rate_transfers,
    cnt_dropout,
    rate_dropout
)
FROM '/raw/fycgr24.dat' DELIMITER '^' CSV NULL '' HEADER;

CREATE INDEX ON grads (school_code);
